//// Requests de Usuarios

### obtener todos los usuarios
GET http://localhost:1234/users


### obtener un usuario por el id
GET http://localhost:1234/users/30


### eliminar un usuario por el id
DELETE  http://localhost:1234/users/4


### crear un usuario
POST http://localhost:1234/users
Content-Type: application/json

{
  "nombre_usuario": "carlosg",
  "clave": "2532243",
  "tipo_usuario": 2,
  "email": "carlosg@gmail",
  "telefono": "345823912",
  "nombre": "Carlos",
  "apellido": "Garcia",
  "direccion": "Brassey 363"
}


### actualizar un usuario
PATCH http://localhost:1234/users/30
Content-Type: application/json

{
  
    "id_usuarios": 30,
    "nombre_usuario": "carlosg",
    "clave": "1234567",
    "tipo_usuario": 2,
    "email": "carlosg@gmail",
    "telefono": "345823912",
    "nombre": "Carlos",
    "apellido": "Garcia",
    "direccion": "Brassey 363"
}


//// Requests de Login

###Post login
POST http://localhost:1234/login
Content-Type: application/json

{
  "nombre_usuario": "admin",
  "clave": "admin"
}

//// Requests de Pedidos
### obtener todos los pedidos
GET http://localhost:1234/orders

### crear un pedido
POST http://localhost:1234/orders
Content-Type: application/json

{
  "id_cliente": 30,
  "total": 1000
}



//// Requests de Servicios

### getall de servicios
GET http://localhost:1234/services


### getone de servicios
GET http://localhost:1234/services/1


### eliminar un servicio por el id
DELETE  http://localhost:1234/services/2


### crear un servicio
POST http://localhost:1234/services
Content-Type: application/json

{
  "desc_servicio": "Arreglo Track Pad",
  "precio": 90000
}


### actualizar un servicio
PATCH http://localhost:1234/services/3
Content-Type: application/json

{
    "precio": 123456
}



//// Requests de Productos

### obtener productos por nombre
GET http://localhost:1234/products/search?nombre_producto=aur

### obtener todos los productos
GET http://localhost:1234/products


### obtener un producto por el id
GET http://localhost:1234/products/13


### eliminar un producto por el id
DELETE  http://localhost:1234/products/13


### crear un producto       !!!!!! agregar autorizacion dentro del controlador
POST http://localhost:1234/products
Content-Type: application/json

{
  "nombre_producto": "Motherboard",
  "desc_producto": "Placa madre re copada",
  "precio": 2000,
  "stock": 2,
  "imagen": "assets/motherboard.jpg"
}


### actualizar un producto    !!!!!! agregar autorizacion
PATCH http://localhost:1234/products/2    
Content-Type: application/json

{
    "stock": 2222
}

//// Requests de login

### login
POST http://localhost:1234/login
Content-Type: application/json

{
  "nombre_usuario": "carlosg",
  "clave": "2532243"
}

//// Requests de Pedidos-Productos

### crear un pedido-producto
POST http://localhost:1234/orders/products
Content-Type: application/json

{
  "id_producto": 12,
  "id_pedidos": 25,
  "cantidad": 5,
  "subtotal": 1000
}
//// Requests de Servicios-Clientes


### Buscar todos los servicios de los clientes

GET http://localhost:1234/services-clients
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImNhcmxvc2ciLCJwYXNzd29yZCI6IjI1MzIyNDMiLCJpYXQiOjE3Mjg2Nzg4NTAsImV4cCI6MTcyODY3OTQ1MH0.mzqPJ8hC67Dp2OhGqIrY7LoTUM08i9VUfwkz4iW8Sdw


### Buscar un servicio de un cliente por id

GET http://localhost:1234/services-clients/1/2/2024-10-08T15:32:00.000Z



### Crear un nuevo servicio de un cliente

POST http://localhost:1234/services-clients
Content-Type: application/json

{
  "id_servicio": 1,
  "id_usuario":2,
  "fecha_servicio":"2024-10-08T15:32:00.000Z",
  "mensaje": "Se necesita arreglar el trackpad"
}


### Borrar un servicio de un cliente por id

DELETE http://localhost:1234/services-clients/1/2/2024-10-08T16:32:00.000Z



### Actualizar un servicio

PATCH http://localhost:1234/services-clients/1/2/2024-10-08T15:32:00.000Z
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImNhcmxvc2ciLCJwYXNzd29yZCI6IjI1MzIyNDMiLCJpYXQiOjE3MjgwNDk0MjUsImV4cCI6MTcyODA1MDAyNX0.cdMq7zJjdLu43V0_lazM4G_CEOFcREOZKgvim2zYTz4
Content-Type: application/json

{
  "mensaje": "Se necesita arreglar el trackpad"
}

### Cantidad de clientes
GET http://localhost:7272/users/clients/quantity
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvcyI6NjcsInRpcG9fdXN1YXJpbyI6MSwidXNlck5hbWUiOiJhZG1pbiIsImlhdCI6MTc0MDQ5NDQ2NywiZXhwIjoxNzQwNDk4MDY3fQ.uKQ7WVRLszFP7BT-gJM8xxPftBJJG2DkuhJdEdGhcUk

### Cantidad de servicios	
GET http://localhost:7272/products/quantity/stock
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvcyI6NjcsInRpcG9fdXN1YXJpbyI6MSwidXNlck5hbWUiOiJhZG1pbiIsImlhdCI6MTc0MDQ5NjMwNywiZXhwIjoxNzQwNDk5OTA3fQ.xsublIVMnC523gyvj2DLQ29Lez_DjSmn6TAr81BAv2Q